<?php
/** @var \Mulwi\Search\Block\Loader $block */
?>

<script type="text/javascript">
    var config = {
        applicationID: "<?= $block->getConfig()->getApplicationID() ?>",
        applicationKey: "<?= $block->getConfig()->getApiKey() ?>",
        baseURL: "<?= $block->getBaseUrl() ?>",
        apiURL: "<?= $block->getConfig()->getApiUrl() ?>",
        display: "iframe",
        activator: {
            selector: ".search-global .search-global-label",
            event: "click",
            prevent: true
        }
    };

    (function (win, doc, type, src, data) {
        var node = doc.createElement(type);
        node.async = 1;
        node.src = src;
        node.dataset.mulwi = JSON.stringify(data);

        var e = doc.getElementsByTagName(type)[0];

        e.parentNode.insertBefore(node, e);
    })(window, document, "script", "<?= $block->getLoaderUrl() ?>", config);
</script>